name: auto-load-qdrant
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: load-vectorstore to qdrant
      - env:
          QDRANT_URL: ${{secrets.QDRANT_URL}}
          QDRANT_API_KEY:  ${{secrets.QDRANT_API_KEY}}
      - run: 
          pip install -r requirements.txt
          python autoload_qdrant.py
